import json
from llm_integration import get_llm_response

print("report_generator.py created with initial imports.")

def generate_investor_report_prompt(
    ticker_symbol: str,
    financial_analysis: str,
    recommendation_details: dict
) -> str:
    """
    Constructs a detailed prompt for the LLM to generate an investor-friendly report.

    Args:
        ticker_symbol (str): The stock ticker symbol.
        financial_analysis (str): The full financial analysis text generated by the LLM.
        recommendation_details (dict): A dictionary containing 'recommendation', 'confidence', and 'rationale'.

    Returns:
        str: A comprehensive prompt for the LLM to generate an investor report.
    """
    recommendation = recommendation_details.get('recommendation', 'Hold')
    confidence = recommendation_details.get('confidence', 50)
    rationale = recommendation_details.get('rationale', 'No specific rationale provided.')

    prompt = f"""You are an expert financial report writer. Based on the following financial analysis and recommendation for {ticker_symbol}, please generate a comprehensive, investor-friendly report.

Your report should be structured with the following sections:

### Executive Summary
- Provide a brief overview of the company's current situation and the main recommendation.

### Key Financial & Technical Insights
- Summarize the most important findings from the historical OHLCV data, technical indicators, and financial statements. Use the provided financial analysis as your primary source.

### Recommendation & Rationale
- Clearly state the recommendation ('{recommendation}') for {ticker_symbol} with a confidence score of {confidence}%.
- Explain the rationale for this recommendation ('{rationale}'), elaborating using details from the financial analysis.

### Potential Risks & Opportunities
- Identify and discuss potential risks and opportunities for the stock based on the provided analysis.

### Visualization Suggestions
- Suggest 2-3 relevant visualizations that would enhance this report. For each visualization, specify:
    - **Type of Chart** (e.g., Line Chart, Bar Chart, Candlestick Chart)
    - **Data Points to Include** (e.g., 'Close Price', 'Volume', 'RSI', 'Revenue', 'Net Income')
    - **Timeframe** (e.g., 'Last 1 Year', 'Last 5 Quarters')
    - **Purpose/Insight** (What story does this visualization tell?)

--- Financial Analysis ---
{financial_analysis}

Your report should be professional, easy to understand for an investor, and leverage the provided analysis effectively. Present the visualization suggestions clearly at the end of the report.
"""
    return prompt

print("generate_investor_report_prompt function added to report_generator.py.")

def generate_investor_report(
    ticker_symbol: str,
    financial_analysis: str,
    recommendation_details: dict
) -> str:
    """
    Generates a comprehensive, investor-friendly report by leveraging an LLM.

    Args:
        ticker_symbol (str): The stock ticker symbol.
        financial_analysis (str): The full financial analysis text generated by the LLM.
        recommendation_details (dict): A dictionary containing 'recommendation', 'confidence', and 'rationale'.

    Returns:
        str: The investor-friendly report generated by the LLM, or an error message.
    """
    print(f"\n--- Generating investor report for {ticker_symbol} ---")
    prompt = generate_investor_report_prompt(ticker_symbol, financial_analysis, recommendation_details)
    report = get_llm_response(prompt)

    if report.startswith("Error:"):
        print(f"Error generating investor report for {ticker_symbol}: {report}")
        return f"Failed to generate investor report for {ticker_symbol}: {report}"

    print(f"Investor report for {ticker_symbol} generated successfully.")
    return report

print("generate_investor_report function added to report_generator.py.")
