import json
from llm_integration import get_llm_response, generate_analysis_prompt

print("recommendation_engine.py created with initial imports.")

def _generate_recommendation_prompt(financial_analysis_text: str, ticker_symbol: str) -> str:
    """
    Constructs a prompt for the LLM to generate a stock recommendation, confidence score, and rationale in JSON format.

    Args:
        financial_analysis_text (str): The detailed financial analysis text generated by the LLM.
        ticker_symbol (str): The stock ticker symbol being analyzed.

    Returns:
        str: A prompt requesting a recommendation in JSON format.
    """
    prompt = f"""Based on the following comprehensive financial analysis for {ticker_symbol}, please provide an explicit 'Buy', 'Sell', or 'Hold' recommendation.
    Also, include a confidence score (an integer from 0 to 100) for your recommendation, and a concise rationale (1-3 sentences) explaining your decision.

    Here is the financial analysis:
    {financial_analysis_text}

    Your output MUST be a JSON object with the following keys:
    - 'recommendation': (string, must be 'Buy', 'Sell', or 'Hold')
    - 'confidence': (integer, 0-100)
    - 'rationale': (string, 1-3 sentences explaining the recommendation)

    Example output:
    ```json
    {{
        "recommendation": "Buy",
        "confidence": 85,
        "rationale": "Strong revenue growth and positive technical indicators suggest upward momentum, despite some market volatility."
    }}
    ```
    """
    return prompt

print("_generate_recommendation_prompt function added to recommendation_engine.py.")

def _parse_recommendation_output(json_string: str) -> dict:
    """
    Parses the JSON string output from the LLM into a Python dictionary, with error handling.

    Args:
        json_string (str): The raw JSON string from the LLM.

    Returns:
        dict: A dictionary containing the recommendation details or a default error structure.
    """
    default_output = {
        "recommendation": "Hold",
        "confidence": 50,
        "rationale": "Could not parse LLM output or recommendation is neutral due to parsing error."
    }
    try:
        # Attempt to find the JSON block in the string (e.g., if wrapped in ```json ... ```)
        if '```json' in json_string and '```' in json_string:
            start = json_string.find('```json') + len('```json')
            end = json_string.find('```', start)
            json_string_clean = json_string[start:end].strip()
        else:
            json_string_clean = json_string.strip()

        parsed_data = json.loads(json_string_clean)

        # Validate required keys
        if all(key in parsed_data for key in ['recommendation', 'confidence', 'rationale']):
            # Further validate types and values
            if parsed_data['recommendation'] in ['Buy', 'Sell', 'Hold'] and \
               isinstance(parsed_data['confidence'], int) and 0 <= parsed_data['confidence'] <= 100 and \
               isinstance(parsed_data['rationale'], str):
                return parsed_data
            else:
                print(f"Warning: Partially invalid data types or values in LLM output: {parsed_data}")
                return default_output
        else:
            print(f"Warning: Missing required keys in LLM output: {parsed_data}")
            return default_output
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON from LLM: {e}\nRaw string: {json_string}")
        return default_output
    except Exception as e:
        print(f"An unexpected error occurred during parsing LLM output: {e}\nRaw string: {json_string}")
        return default_output

print("_parse_recommendation_output function added to recommendation_engine.py.")

def generate_stock_recommendation(ticker_symbol: str, normalized_data: str) -> dict:
    """
    Generates a stock recommendation along with a confidence score and rationale,
    based on financial analysis performed by an LLM.

    Args:
        ticker_symbol (str): The stock ticker symbol.
        normalized_data (str): The preprocessed financial and technical data for the ticker.

    Returns:
        dict: A dictionary containing the recommendation, confidence, rationale,
              and the full financial analysis text from the LLM.
    """
    print(f"\n--- Generating financial analysis for {ticker_symbol} ---")
    # Step 1: Get detailed financial analysis from LLM
    analysis_prompt = generate_analysis_prompt(normalized_data, ticker_symbol)
    financial_analysis_text = get_llm_response(analysis_prompt)

    if financial_analysis_text.startswith("Error:"):
        print(f"Error during financial analysis for {ticker_symbol}: {financial_analysis_text}")
        return {
            "recommendation": "Hold",
            "confidence": 50,
            "rationale": f"Failed to get financial analysis: {financial_analysis_text}",
            "full_analysis": financial_analysis_text
        }

    print(f"--- Generating recommendation for {ticker_symbol} ---")
    # Step 2: Get recommendation from LLM based on analysis
    recommendation_prompt = _generate_recommendation_prompt(financial_analysis_text, ticker_symbol)
    raw_recommendation_output = get_llm_response(recommendation_prompt)

    if raw_recommendation_output.startswith("Error:"):
        print(f"Error during recommendation generation for {ticker_symbol}: {raw_recommendation_output}")
        return {
            "recommendation": "Hold",
            "confidence": 50,
            "rationale": f"Failed to get recommendation: {raw_recommendation_output}",
            "full_analysis": financial_analysis_text
        }

    # Step 3: Parse the recommendation output
    parsed_recommendation = _parse_recommendation_output(raw_recommendation_output)

    # Add the full analysis to the returned dictionary
    parsed_recommendation["full_analysis"] = financial_analysis_text

    print(f"Recommendation for {ticker_symbol}: {parsed_recommendation.get('recommendation')}, Confidence: {parsed_recommendation.get('confidence')}%")
    return parsed_recommendation

print("generate_stock_recommendation function added to recommendation_engine.py.")
